#!/usr/bin/env python3
"""One-way retirement of known generated Make artifacts; never invokes Make."""

import hashlib
import json
import os
from pathlib import Path
import stat
import sys
import tempfile

BEGIN = b"# makevn:begin\n"
END = b"# makevn:end\n"
BLOCK = BEGIN + b"include .makevn/makevn.mk\n" + END
BOOTSTRAP = b"# Generated by makevn. Remove with `makevn uninstall`.\ninclude .makevn/makevn.mk\n"
# Historical template bodies (first line contains the installation-specific binary).
KNOWN_BODIES = {
    "41487110bb0bb1d8976168a02cd144ed88145f355a5660de6316e0ce9c8d50a1",
    "490b1cd0bcb01fdb66b05699f9b845962828e2f339431c57df2afbb6d2eb9bf4",
    "66b486c0041a6b73fab1fc6ac8b38555de7bcb7ff239389d3293e654aa8474c8",
    "68304ccbd530282b81ede549471736b3e52a379f6b2e138c154afa2f91bad100",
    "8a4207fde9818a29ccc195a70d11414419aa6dad0f670788d9fbc12a7ab49215",
    "8b627d408e0470b38d5a4291fd1370da18cbd04136c8af73d4d109c835781367",
    "92525944a7f4bec881df8e1e2345afee371931514e6b8e707882bb96c8225401",
    "95857fab4d6fe643ab92676a6c553c8ce8256ecd700ff80ce110a24c37b40353",
    "a83517fac51cbfa1fd774d7278ce5272078248c007c2c0e5ff45f4e476c178b6",
    "b22280fd0aeb4171f150f7514665f9abcf08f8ea0d631a61c7d6428c3544b795",
    "d02e0419e0ab83f8d7e4609d169e33d3e61434ec4bcde72757a61860764e6366",
    "e3144ba9962c967c1666be9d239fca6e6ee5e898d2ccfbfb7090ec64579939a9",
    "e7b64bb52b97d6bd91321a22f3d32365b59870a55bd47009fc6137fc5f1591fd",
    "eb9744b5b6f16a0e98b4b23ef78d21b51522f0a8a08d7b676390562a65f6bb88",
    "ff1d7d5ebdd19b372cadef45182a461b042c6fe607a26b544f79f2db58973ec0",
}


def refuse(path, reason):
    raise ValueError(
        f"Legacy Make retirement blocked: {path}: {reason}. "
        "No files changed. Resolve the legacy include/artifact manually, then retry "
        "makevn init --force (or uninstall). Preserve your custom targets."
    )


def regular(path):
    if path.is_symlink():
        refuse(path, "symbolic links are not safe to migrate")
    if path.exists() and not path.is_file():
        refuse(path, "expected a regular file")
    return path.exists()


def legacy_fields(state_dir):
    manifest = state_dir / "manifest"
    state = state_dir / "state.json"
    values = {}
    if regular(manifest):
        for line in manifest.read_text().splitlines():
            key, sep, value = line.partition("=")
            if sep and key in ("managed_makefile", "generated_root_makefile"):
                if key in values:
                    refuse(manifest, "duplicate legacy field")
                values[key] = value
    if regular(state):
        # Standalone state is unrelated to migration, but old state may be the
        # only surviving ownership record in a partially initialized repository.
        data = json.loads(state.read_text())
        if not isinstance(data, dict):
            refuse(state, "expected an object ownership record")
        for key in ("managed_makefile", "generated_root_makefile"):
            if key not in data:
                continue
            if key in values and values[key] != data[key]:
                refuse(state, "legacy ownership records disagree")
            values[key] = data[key]
    managed = values.get("managed_makefile", "")
    generated = values.get("generated_root_makefile", "")
    if managed not in ("", "Makefile", "GNUmakefile"):
        refuse(manifest, "unsafe managed_makefile path")
    if generated not in ("", "Makefile"):
        refuse(manifest, "unsafe generated_root_makefile path")
    if managed and generated:
        refuse(manifest, "conflicting ownership records")
    return managed, generated


def plan_retirement(repo):
    state_dir = repo / ".makevn"
    if state_dir.is_symlink():
        refuse(state_dir, "symbolic state directory")
    if state_dir.exists() and not state_dir.is_dir():
        refuse(state_dir, "expected a directory")
    # Initialization/uninstall must not follow state-file symlinks either.
    for name in ("config", "profile.env", "manifest", "state.json"):
        regular(state_dir / name)
    managed, generated = legacy_fields(state_dir)
    actions = []
    for name in ("Makefile", "GNUmakefile"):
        path = repo / name
        # Unrelated user-owned Makefiles, including symlinks, are never touched.
        tracked = name in (managed, generated)
        if path.is_symlink() and not tracked:
            # An untracked symlink is not inspected or migrated. A remaining
            # generated include could still reference it, so refuse that case.
            if (state_dir / "makevn.mk").exists():
                refuse(path, "untracked symlink with legacy artifacts")
            continue
        if not regular(path):
            continue
        content = path.read_bytes()
        if generated == name:
            if content != BOOTSTRAP:
                refuse(path, "generated bootstrap has been modified")
            actions.append((path, None))
            continue
        has_markers = b"# makevn:begin" in content or b"# makevn:end" in content
        if has_markers:
            if not tracked or content.count(BEGIN) != 1 or content.count(END) != 1:
                refuse(path, "unknown or incomplete managed block")
            if content.count(BLOCK) != 1:
                refuse(path, "managed block has been modified")
            updated = content.replace(BLOCK, b"", 1)
            if b".makevn/makevn.mk" in updated or b"# makevn:" in updated:
                refuse(path, "additional legacy references remain")
            actions.append((path, updated))
        elif b".makevn/makevn.mk" in content:
            refuse(path, "unmanaged legacy include")
    include = state_dir / "makevn.mk"
    if regular(include):
        header, sep, body = include.read_bytes().partition(b"\n")
        if not sep or not header.startswith(b"MAKEVN_BIN ?= "):
            refuse(include, "unknown generated header")
        if hashlib.sha256(body).hexdigest() not in KNOWN_BODIES:
            refuse(include, "generated template has been modified or is unknown")
        actions.append((include, None))
    return actions


def retire(repo, dry_run):
    actions = plan_retirement(repo)
    if dry_run:
        for path, content in actions:
            operation = "remove" if content is None else "remove managed block from"
            print(f"would {operation}: {path.relative_to(repo)}")
        return
    # Stage replacements before changing any original; preserve bytes/mode of
    # repository-owned files outside the exact known generated block.
    staged = []
    try:
        for path, content in actions:
            if content is None:
                continue
            fd, temporary = tempfile.mkstemp(prefix=".makevn-retire-", dir=path.parent)
            staged.append((path, Path(temporary)))
            with os.fdopen(fd, "wb") as stream:
                stream.write(content)
            os.chmod(temporary, stat.S_IMODE(path.stat().st_mode))
        for path, temporary in staged:
            os.replace(temporary, path)
        for path, content in actions:
            if content is None:
                path.unlink()
        if actions:
            print("Retired legacy generated Make artifacts.")
    finally:
        for _, temporary in staged:
            temporary.unlink(missing_ok=True)


if __name__ == "__main__":
    try:
        retire(Path(sys.argv[1]), sys.argv[2] == "true")
    except (ValueError, OSError) as error:
        print(str(error), file=sys.stderr)
        sys.exit(1)
